[package]
name = "wasmedge-tf-example-mobilenet"
version = "0.1.0"
authors = ["Second-State"]
readme = "README.md"
edition = "2021"
publish = false

[dependencies]
wasmedge_tensorflow_interface = "0.3.0"
wasi-nn = "0.1.0"
bytemuck = "1.13.1"
[workspace]
